# Generated by Django 3.2.8 on 2021-10-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('emp_name', models.CharField(max_length=30)),
                ('emp_mobile', models.IntegerField()),
                ('emp_email', models.EmailField(max_length=254)),
                ('emp_sal', models.IntegerField()),
                ('emp_add', models.TextField(max_length=100)),
            ],
        ),
    ]
