# Generated by Django 3.2.8 on 2021-11-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'other')], max_length=10, null=True),
        ),
    ]
