# Generated by Django 3.2.8 on 2021-11-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_employee_emp_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F'), ('Other', 'O')], default=('Female', 'F'), max_length=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.position'),
        ),
    ]
