# Generated by Django 3.2.8 on 2021-11-22 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0004_auto_20211122_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_awards',
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_experience',
            field=models.CharField(choices=[('0', 'Fresher'), ('3', 'three months'), ('6+', 'Six months +')], default=0, max_length=20),
        ),
        migrations.DeleteModel(
            name='Awards',
        ),
    ]
