# Generated by Django 3.2.8 on 2021-11-23 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0007_auto_20211123_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_nick',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.nick'),
        ),
    ]
