# Generated by Django 4.0.4 on 2022-05-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0008_auto_20211123_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_add',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='nick',
            name='title',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='tittle',
            field=models.CharField(max_length=10),
        ),
    ]
