# Generated by Django 4.0.4 on 2022-05-11 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0010_alter_employee_emp_add_alter_employee_emp_awards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='tittle',
            new_name='title',
        ),
    ]
